### ISSUE TITLE
Extra large bottom margin in generated section heading in 0.22.4

### ISSUE THREAD

**Issue by kianmeng** [elixir-lang/ex_doc#1272]
The latest version, `0.22.4` seems to generate section heading with large bottom margin which looks slightly off and weird, especially with a list. 

Is this a new intended layout or a bug?

## 0.22.4

![image](https://user-images.githubusercontent.com/134518/93015799-f6cef000-f5ee-11ea-8ea9-b865440e2f0d.png)

## 0.22.2

![image](https://user-images.githubusercontent.com/134518/93015807-0817fc80-f5ef-11ea-9669-4ad1909d2a95.png)

**Comment by josevalim** [comment]
It is definitely a bug. Have you published these docs anywhere so we can take a look at them? :)

**Comment by josevalim** [comment]
No worries, I have fixed them on master. New release incoming, thanks!

**Comment by kianmeng** [comment]
@josevalim Did I miss something in my test? The problem still exists in `0.22.5`.

![image](https://user-images.githubusercontent.com/134518/93344456-4c600280-f864-11ea-943b-0296ea383a8c.png)

```
$ mix deps.tree
test
└── ex_doc == 0.22.5 (Hex package)
    ├── earmark_parser ~> 1.4.0 (Hex package)
    └── makeup_elixir ~> 0.14 (Hex package)
        └── makeup ~> 1.0 (Hex package)
            └── nimble_parsec ~> 0.5 (Hex package)
```

**Comment by josevalim** [comment]
You are correct, I forgot to recompile assets. My bad.

**Comment by josevalim** [comment]
Done!
