### ISSUE TITLE
html documentation presentation suggestions

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ex_doc#606]
Following discussion on erlang-questions, I looked a little at the docs CSS and I have some comments.

- the main site has text size set to 0.8em, why? It is quite small.

- some font sizes and height lines are hardcoded (px, not em), for example 'code' elements 
- IMHO line height can be made 1.4em (maybe even 1.3) without impairing legitibility
- .content-inner pre has "overflow-x: scroll;", changing it to "auto" will remove the scrollbar when not needed. 
- it would look even nicer to have the function docs content indented a bit, like the erlang docs do. It helps scanning the page faster.

Originally reported by @vladdu here: https://github.com/elixir-lang/elixir/issues/5265

**Comment by josevalim** [comment]
Thank you @vladdu for the report. Replies inline.

> some font sizes and height lines are hardcoded (px, not em), for example 'code' elements

I will look into it. Also a pull request here would be appreciated. :) 

> .content-inner pre has "overflow-x: scroll;", changing it to "auto" will remove the scrollbar when not needed.

This has been fixed in master. Please access http://elixir-lang.org/docs/master/elixir/Kernel.html and hit a hard reload and let us know how it goes.

> IMHO line height can be made 1.4em (maybe even 1.3) without impairing legitibility

Where is line-height 1.4em? For content it seems to be 1.68em.

> it would look even nicer to have the function docs content indented a bit, like the erlang docs do. It helps scanning the page faster.

To move the discussion on this, here is how it looks with them indented:

<img width="947" alt="screen shot 2016-09-28 at 11 54 15" src="https://cloud.githubusercontent.com/assets/9582/18909041/5b43b418-8572-11e6-9e1e-957cdb252800.png">

**Comment by vladdu** [comment]
I'll look at submitting a PR, but my Less skills aren't good. Hopefully, just checking for font sizes won't require much :-)

>> IMHO line height can be made 1.4em (maybe even 1.3) without impairing legitibility
> Where is line-height 1.4em? For content it seems to be 1.68em.

I meant that it could be made 1.4 from 1.68. 

The vertical space is most as a premium on today's monitors, so every little bit helps. There are also element margins that could be made narrower.

Regarding the indentation, I'd do a level more, that is having "specs" and "examples" look more like headers. The indentation for these headers need not be large (because the function name is visible enough), but the content under them could have something like 2em.

**Comment by josevalim** [comment]
> I'll look at submitting a PR, but my Less skills aren't good. Hopefully, just checking for font sizes won't require much :-)

Oh, that's a great starting point. Don't worry, I will get started on that.

> I meant that it could be made 1.4 from 1.68.

I will run with those settings locally and let you know how it goes. But at first I was not happy with them. Specially if we increase the font-size (which I was already trying giving your initial report). :D

**Comment by josevalim** [comment]
I have used em in fonts and indent the function contents, those should be in the Elixir master documentation overnight. I will give it a try with a bigger font and smaller line-height locally and push it later on depending on the results. Thank you!

**Comment by josevalim** [comment]
@vladdu I have pushed to master the changes so far. I had to revert some of the px -> em changes because they had unwarranted side effects. I kept the code ones. I have also indented the function information as in the screenshot for more feedback.

**Comment by vladdu** [comment]
Thanks. Some things are hard to see without several examples and context, and still not everyone will agree with the result.

**Comment by josevalim** [comment]
@vladdu yup! and I also let things run locally (and later online) at least a week because our first reaction to most of those things is to think "everything is worse now", haha.
