### ISSUE TITLE
Keyboard shortcuts - localization for "/" & "?"

### ISSUE THREAD

**Issue by cw789** [elixir-lang/ex_doc#997]
Hey the new keyboard shortcuts are very cool,
but on my german (de-AT) keyboard the "/" and "?" are not working.

Quick research:
Keycode for "/" is 55 (with shift).
Keycode for "?" is 219 (with shift).

Implementation: [keyboard-shortcuts.js](lang/ex_doc/blob/27ad5b60fc127d77eb6152a895236d8c89cae441/assets/js/keyboard-shortcuts.js)

I can have a look at it.

**Comment by josevalim** [comment]
We have fixed this on master already, thank you!

**Comment by cw789** [comment]
This issue isn't fixed.

I would suggest to refactor "keyboard-shortcuts.js" using `KeyboardEvent.key` instead of `keydown.keyCode`.
Even if `KeyboardEvent` is still a working-draft it seems to have a good support: [caniuse](https://caniuse.com/#feat=keyboardevent-key)

**Comment by cybrox** [comment]
FYI, for `/`, you can use `s`, since it's just an alias.

However, it is still an inconvenience and I do agree that should be fixed, so that shortcuts are consistent for de-DE/de-CH keyboards as well.

Regarding browser support, I don't think there's anything keeping us from using `KeyboardEvent.key` on top of the current implementation and using `keydown.keyCode` as fallback.

**Comment by cw789** [comment]
I've not tested it properly but the following change within `keyboard-shortcuts.js` should do the trick:

```
const key = event.key
const foundShortcut = find(keyboardShortcuts, function (shortcut) {
  if (key) return shortcut.name === key

  // legacy fallback
  const isShiftRequired = !!shortcut.requiresShiftKey
  return shortcut.keyCode === keyCode && isShiftRequired === isShiftPressed
})
```
